#Current Dir here means where ExtentSpark.html is placed
#you can write ./reports or only reports
extent.reporter.spark.start=true
extent.reporter.spark.out=./reports/ExtentSpark.html
screenshot.dir=./reports/screenshots/
screenshot.rel.path=./screenshots/
